#!/bin/bash
#
# chkconfig: 35 90 12
# description: Foo server
#

# Get function from functions library
. /etc/init.d/functions

SERVICE="node_exporter"


# Start the Node Exporter service
start() {
        initlog -c "echo -n Starting Node Exporter service: "
        /usr/local/bin/$SERVICE  &
        ### Create the lock file ###
        touch /var/run/node_exporter.pid
        success $"Node Exporter service starts"
        echo
}

# Restart the service FOO
stop() {
        initlog -c "echo -n Stopping Node Exporter service: "
        killproc $SERVICE
        ### Now, delete the lock file ###
        rm -f /var/run/node_exporter.pid
        echo
}

### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status $SERVICE
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0