#!/bin/bash
#
# chkconfig: 35 90 12
# description: Foo server
#

# Get function from functions library
. /etc/init.d/functions

SERVICE="alertmanager"
CONFIG_FILE="/etc/alertmanager/alertmanager.yml"

# Start the alertmanager service
start() {
        initlog -c "echo -n Starting alertmanager service: "
        /usr/local/bin/alertmanager --config.file="$CONFIG_FILE" &
        ### Create the lock file ###
        touch /var/run/alertmanager.pid
        success $"alertmanager service starts"
        echo
}

# Restart the service FOO
stop() {
        initlog -c "echo -n Stopping alertmanager service: "
        killproc $SERVICE
        ### Now, delete the lock file ###
        rm -f /var/run/alertmanager.pid
        echo
}

### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status $SERVICE
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0